[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "asmjit"
version = "0.1.0"
readme = "INTRO"
requires-python = ">=3.14"
dependencies = []

[tool.basedpyright]
reportUnusedExpression = "none"
reportImplicitRelativeImport = "none"

[tool.ruff.lint]
ignore = ["I001"]
