[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "asmjit"
version = "0.1.0"
readme = "INTRO"
requires-python = ">=3.14"
dependencies = []

[[tool.setuptools.ext-modules]]
name = "asmjit.utils"
sources = ["src/asmjit/utils.c"]
extra-compile-args = ["-O3"]

[tool.basedpyright]
extraPaths = ["src"]
reportUnusedExpression = "none"
reportImplicitRelativeImport = "none"
reportMissingModuleSource = "none"

[tool.pyright]
extraPaths = ["src"]
reportMissingModuleSource = "none"

[tool.ruff.lint]
ignore = ["I001"]
