[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
readme = "README.md"
license = "GPL-3.0-only"
requires-python = ">=3.14"
dependencies = []

[[tool.setuptools.ext-modules]]
name = "jitasm.utils"
sources = ["src/jitasm/utils.c"]
extra-compile-args = ["-O3"]

[tool.basedpyright]
extraPaths = ["src"]
reportUnusedExpression = "none"
reportImplicitRelativeImport = "none"
reportMissingModuleSource = "none"

[tool.pyright]
extraPaths = ["src"]
reportMissingModuleSource = "none"

[tool.ruff.lint]
ignore = ["I001"]
